apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  # ArgoCD Notifications v0.7.0
  - github.com/argoproj-labs/argocd-notifications/manifests/controller?ref=adebb564b4cd70b3f5a1ea183204672ed2e5f1f4
  - service-monitor.yaml
patches:
  - cm-patch.yaml
images:
  - name: argoprojlabs/argocd-notifications:v0.7.0
    digest: sha256:53f7e184fea1c3fd33ae4bd57eb6bb9b58b4d366a5dc8b3c7905c183ca010f4d
generators:
  - secret-generator.yaml
