apiVersion: apps/v1
kind: Deployment
metadata:
  name: webirc
  labels:
    app: webirc
spec:
  selector:
    matchLabels:
      app: webirc
  template:
    metadata:
      labels:
        app: webirc
    spec:
      containers:
      - name: webirc
        image: hashbang/webirc
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
---
apiVersion: v1
kind: Service
metadata:
  name: webirc
  labels:
    app: webirc
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: webirc
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: webirc-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    external-dns.alpha.kubernetes.io/hostname: webirc.hashbang.sh
spec:
  tls:
  - hosts:
    - webirc.hashbang.sh
    secretName: webirc-tls
  rules:
  - host: webirc.hashbang.sh
    http:
      paths:
      - path: /
        backend:
          serviceName: webirc
          servicePort: 80
