apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: website
resources:
- namespace.yaml
- resources.yaml
- ingress.yaml
configMapGenerator:
- name: opaque-config
  files:
  - files/config.yaml
