apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: site
resources:
  - namespace.yaml
  - resources.yaml
  - networkpolicy.yaml
replicas:
  - name: site
    count: 2
images:
  - name: hashbang/hashbang.sh
    digest: sha256:5d23915284c0c396b1bff1289016056eda16e036079633d13a0cd58887b21872
