apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-controller
data:
  http-snippet: >-
    proxy_cache_path /tmp/nginx-cache
    levels=1:2
    keys_zone=cache:10m
    max_size=1G
    inactive=60m
    use_temp_path=off;
