apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
bases:
- ../../../../kustomizations/ingress-nginx
resources:
- namespace.yaml
patches:
- path: ingress-nginx-controller-configmap.patch.yaml
  target:
    kind: ConfigMap
    name: ingress-nginx-controller
