apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ircd
resources:
  - namespace.yaml
  - certificate.yaml
  - resources.yaml
configMapGenerator:
- name: irc-config
  options:
    disableNameSuffixHash: true
  files:
  - files/ircd.motd
  - files/ircd.yaml
images:
  - name: oragono/oragono:latest
    digest: sha256:f3dbcfc77fa839414b3fe4335eaf724fd476484489ccfbba273fd04092bc60fa
