apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ircd
resources:
  - namespace.yaml
  - certificate.yaml
  - resources.yaml
configMapGenerator:
- name: irc-config
  files:
  - files/ircd.motd
  - files/ircd.yaml
# TODO: move inside of `configMapGenerator` once kustomize 3.5.5 is available
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: oragono/oragono:dev
    digest: sha256:dd62a8ea7776c6951673cbe0318125651e8395232f1b8b709228ed6197f528ff
