apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # release-0.4; held back due to 0.5 not supporting Kubernetes 1.18
  - github.com/coreos/kube-prometheus?ref=ee8077db04965d6b4d9e6a328d5283dd6ba71d33
  - cilium-service-monitor.yaml
patches:
  - cluster-wide.patch.yaml
  - grafana-dashboards.patch.yaml
configMapGenerator:
  - name: grafana-dashboard-argocd
    files:
      # From https://github.com/argoproj/argo-cd/blob/master/examples/dashboard.json
      - files/grafana-dashboard-argocd.json
  - name: grafana-dashboard-cilium
    files:
      # https://github.com/cilium/cilium/tree/6fe8d092a6796d36230a0e3480cd2a8472e1a6f0/examples/kubernetes/addons/prometheus/files/grafana-config
      - files/grafana-dashboard-cilium.json
      - files/grafana-dashboard-cilium-operator.json
# TODO: move inside of `configMapGenerator` once kustomize 3.5.5 is available
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: grafana/grafana:6.4.3
    digest: sha256:bd55ea2bad17f5016431734b42fdfc202ebdc7d08b6c4ad35ebb03d06efdff69
  - name: quay.io/coreos/configmap-reload:v0.0.1
    digest: sha256:e2fd60ff0ae4500a75b80ebaa30e0e7deba9ad107833e8ca53f0047c42c5a057
  - name: quay.io/coreos/k8s-prometheus-adapter-amd64:v0.5.0
    digest: sha256:5882cda1ee0a8e65e7df4af93a7a1cf36ade9108ee35ef155d7009dc6eaad8a0
  - name: quay.io/coreos/kube-rbac-proxy:v0.4.1
    digest: sha256:9d07c391aeb1a9d02eb4343c113ed01825227c70c32b3cae861711f90191b0fd
  - name: quay.io/coreos/kube-state-metrics:v1.9.2
    digest: sha256:99e18bb3ca7344cb8ece2b5ced2599d561d2de2306531366e8198364d17b0f22
  - name: quay.io/coreos/prometheus-config-reloader:v0.34.0
    digest: sha256:459bc1b1fc51420cd244b082fe14444f6d8596997c2e40f52c08d1f5a09ab860
  - name: quay.io/coreos/prometheus-operator:v0.34.0
    digest: sha256:c0bcb231fe67cd11fd26f7adf5ac1080dfac189ac94705538bd4ab7dd99a98a9
  - name: quay.io/prometheus/alertmanager:v0.18.0
    digest: sha256:3d52ab7ef3a2e23e26a73cfd0ce13189e3796fb276b9af3e79664e4f743d8a1d
  - name: quay.io/prometheus/node-exporter:v0.18.1
    digest: sha256:a2f29256e53cc3e0b64d7a472512600b2e9410347d53cdc85b49f659c17e02ee
  - name: quay.io/prometheus/prometheus:v2.11.0
    digest: sha256:b6275644820cf7a256cd9502eafb35a0b1862b59a3c49afb8267f75ffe79efcc
