apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/coreos/kube-prometheus?ref=7d5d6d6a6315ad2f1fbdd87777dd05c3cdfc4a75 # Random master commit that supports Kubernetes 1.18
  - ingress.yaml
  - cilium-service-monitor.yaml
  - ./loki
  - ./promtail
  - prometheus-additional-targets.yaml
patches:
  - container-images.patch.yaml
  - cluster-wide.patch.yaml
  - grafana-dashboards.patch.yaml
  - prometheus-additional-scrape-configs.patch.yaml
  - prometheus-persistent-volume.patch.yaml
patchesJson6902:
  - target:
      version: v1
      kind: Service
      namespace: monitoring
      name: grafana
    patch: |-
      - op: replace
        path: /spec/ports/0/port
        value: 80
  # Workaround https://github.com/coreos/kube-prometheus/issues/586
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: alertmanagers.monitoring.coreos.com
    patch: |-
      - op: remove
        path: /status
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: podmonitors.monitoring.coreos.com
    patch: |-
      - op: remove
        path: /status
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: prometheuses.monitoring.coreos.com
    patch: |-
      - op: remove
        path: /status
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: prometheusrules.monitoring.coreos.com
    patch: |-
      - op: remove
        path: /status
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: servicemonitors.monitoring.coreos.com
    patch: |-
      - op: remove
        path: /status
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: thanosrulers.monitoring.coreos.com
    patch: |-
      - op: remove
        path: /status
configMapGenerator:
  - name: grafana-dashboard-argocd
    options:
      disableNameSuffixHash: true
    files:
      # From https://github.com/argoproj/argo-cd/blob/master/examples/dashboard.json
      - files/grafana-dashboard-argocd.json
      # From https://argoproj-labs.github.io/argocd-notifications/grafana-dashboard.json
      - files/grafana-dashboard-argocd-notifications.json
  - name: grafana-dashboard-cilium
    options:
      disableNameSuffixHash: true
    files:
      # https://github.com/cilium/cilium/tree/6fe8d092a6796d36230a0e3480cd2a8472e1a6f0/examples/kubernetes/addons/prometheus/files/grafana-config
      - files/grafana-dashboard-cilium.json
      - files/grafana-dashboard-cilium-operator.json
  - name: grafana-dashboard-ingress-nginx
    options:
      disableNameSuffixHash: true
    files:
      # https://github.com/kubernetes/ingress-nginx/blob/810acfafbef86d9dc05e0ece68c97d0c93344632/deploy/grafana/dashboards/nginx.json
      - files/grafana-dashboard-ingress-nginx.json
  - name: grafana-dashboard-userdb
    options:
      disableNameSuffixHash: true
    files:
      # feel free to follow @IAmRyanSquared
      - files/grafana-dashboard-userdb.json
  - name: grafana-dashboard-shell-nodes
    options:
      disableNameSuffixHash: true
    files:
      # modified from https://raw.githubusercontent.com/grafana/kubernetes-app/master/src/dashboards/k8s-node.json
      - files/grafana-dashboard-shell-nodes.json
secretGenerator:
  - name: grafana-datasources
    namespace: monitoring
    behavior: merge
    options:
      disableNameSuffixHash: true
    files:
      - files/datasource-loki.yaml
generators:
  - secret-generator.yaml
images:
  - name: grafana/grafana:7.1.0
    digest: sha256:174987125ca36f8de41184267d15b7a68c65c19be6979bfaa0b49f205f58f479
  - name: quay.io/coreos/k8s-prometheus-adapter-amd64:v0.5.0
    digest: sha256:5882cda1ee0a8e65e7df4af93a7a1cf36ade9108ee35ef155d7009dc6eaad8a0
  - name: quay.io/coreos/kube-rbac-proxy:v0.4.1
    digest: sha256:9d07c391aeb1a9d02eb4343c113ed01825227c70c32b3cae861711f90191b0fd
  - name: quay.io/coreos/kube-state-metrics:v1.9.2
    digest: sha256:99e18bb3ca7344cb8ece2b5ced2599d561d2de2306531366e8198364d17b0f22
  - name: quay.io/coreos/prometheus-operator:v0.34.0
    digest: sha256:c0bcb231fe67cd11fd26f7adf5ac1080dfac189ac94705538bd4ab7dd99a98a9
  - name: quay.io/prometheus/node-exporter:v0.18.1
    digest: sha256:a2f29256e53cc3e0b64d7a472512600b2e9410347d53cdc85b49f659c17e02ee
