apiVersion: v1
kind: Secret
metadata:
  name: additional-scrape-configs
type: Opaque
stringData:
  prometheus-additional.yaml: |
    - job_name: "shell-server"
      metrics_path: /metrics
      static_configs:
      - targets:
        - de1.hashbang.sh
