apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  namespace: monitoring
  name: k8s
spec:
  # Hash lock prometheus container
  sha: b6275644820cf7a256cd9502eafb35a0b1862b59a3c49afb8267f75ffe79efcc
  # Hash lock helper containers
  containers:
    - name: prometheus-config-reloader
      image: quay.io/coreos/prometheus-config-reloader@sha256:459bc1b1fc51420cd244b082fe14444f6d8596997c2e40f52c08d1f5a09ab860
    - name: rules-configmap-reloader
      image: quay.io/coreos/configmap-reload@sha256:e2fd60ff0ae4500a75b80ebaa30e0e7deba9ad107833e8ca53f0047c42c5a057
    # - name: thanos-sidecar
    #   image:
