apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: userdb-api
resources:
- namespace.yaml
- resources.yaml
generators:
  - secret-generator.yaml
replicas:
- name: userdb-api-deployment
  count: 3
