apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: userdb-api
resources:
- namespace.yaml
- resources.yaml
- service-monitor.yaml
generators:
  - secret-generator.yaml
replicas:
- name: userdb-api-deployment
  count: 2
images:
- name: postgrest/postgrest:v7.0.1
  digest: sha256:2a10713acc388f9a64320443e949eb87a0424ab280e68c4ed4a6d0653c001586
