apiVersion: v1
kind: Secret
metadata:
    name: postgrest-secrets
type: Opaque
stringData:
    db-uri: ENC[AES256_GCM,data:sk1tVn62ud/g7Qg/gpu8bugIy3YRxrPoRxPqs/Kk4gzjjJnpCfFJt8ZGHxMhcrWCoNO+IF+2/UIXvOVGtyQvXqs75kQxP8DcV5wXUBF6ldkwArO8NJJbpuUtSqWkfE2Qlr1vMqIiRh3ghTt+Ylm1G6Vz32Nqr9Yvfij37w==,iv:UNSbQ+pnPy8TYnCaLgk1fl4EY/1PkkVchQY/oXPKS4E=,tag:cgtatKdbZafWkTgAqZ9PHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-05-26T14:08:07Z'
    mac: ENC[AES256_GCM,data:BjjxUFWBCDJXdS6ikGrU3fL/hFi4u86W6ae7XouVd65s8mjKy58rNOvb4ZcZbi5rDCQjCCUAkMiKlR52Yd+R856o7sC4ee7zK1javXpnC/N1O0oo2rmKbTXUDeV0ZIk1CIH+uByXtoxrZCoV8U6bOlFzQJRdcliFNbwoGE776C0=,iv:+XlRf9tI3dnA/uLztpMEyGUfi1m/iYY7V+FcaGYk6hU=,tag:NOCVz6JK6c2hMLUUIlj7ig==,type:str]
    pgp:
    -   created_at: '2020-05-27T02:00:42Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+pWRuJw67SWARAApgMt684CG0cfZIVHBItNE0w+ZBFPDNR6c2bJ7xU5UQ60
            3bQbwEtr5VX08U9J8/6u4grD/t70ZGAPS5ozKLr1CXh0gFRVAh8pNLedKeiB/3et
            LK9wDUwauWTB89OdfbPph3rspyTSCQCXcT0gmGQ9vSy5q3C0FxSQ+tNnQcDbtWii
            14zmNLqM7iMJo4Merakebiit3ziZ/8ireaqJx7q0/MhdKFtpP/3u/FqYrtBDqPmT
            pMTwNR+3ufBRdcBH8QswaqHRu1bBTfnhze2ar1vlzOTLpGRy35MwZxrEAeC39EQz
            sPBLFBVDdfM1HHTTeX0n33ml6P1kCSePTHb5bpjyDT1O2duo4BbizQWgRu7fjTMn
            ZSSYmE7dgAR2LzPqfZOIsgn1oj1JytZ6Qwrdn4NrA6ILbvJCmyjDIytJho9FZ2Oq
            bwe1rSmFR44e9MJTPBhGOmCk0fMEmNl2awSVGpIR+8hlmS+3ZARw4QAvptZIqJIn
            6RRyHm9s3vlULRK2MswbjFk06UaN8haHGTWwCHhd6n28nTuE7Eb7C4WcrtTGw1+i
            Lofvli/Qj+mI2EodXsA7J0S9g908Wm6ZLWrhEcOFMC1LuP1unQmN2bdHr+g7iCZi
            RX+W4FHXKHRUpLzxWcN+do14P4UUCcN39Ml9nMkLgbmC34WOsgHQt/muPDatLjrS
            XAERYe8ohygXQYeDqzqxHveO0NG+a5J0iZNwiA8FySRSkeGIoEJD03OjOCzPAzwV
            tNHA6yv4pcWr1ECNIadK3OQFWyNnf/0H+fILriKtgbzEBGVWvhUxP3Jd7PnX
            =KWyd
            -----END PGP MESSAGE-----
        fp: 1FD6667A0808D4D48BDB8757A61B48D8288FCF8A
    -   created_at: '2020-05-27T02:00:42Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA4FedWMNSzdLARAAFcfHrRBxpt/4TPmj3+XU1xrNKDlDDcioX1jdu7wxVbdt
            w8T5avicnsoLSTOUFceFQWzU9fes/3r02QRxRJ8uzOx7g39C+YiLIRyZd9TgoVhS
            Pwww0lJycnPlGPvFgS0WVlje7OCYtdtv57xn70vbyG+b0i03geFhkE/PEX7CL13V
            JKMxGF7zvU++DmEfy7mJhSjm3mhu27CO49WN2NcBxYFSdUIWZjQPLU93ZoBqbL8C
            1WyYm30HHbe9OyBBNkblcVoVD8yuWkBDm1J+QjccMx7kNT6UiivoQkEHbD0YEk8D
            SiTJbLQzBTsDq1v0oos05ENOcadhseEItiZjYNLSOW5swa+Ggzi9tLx+ndBlpREl
            l+jLNmB6fPzcdHvs6Ej3zB4+9C/y133GFcSYB1fCDHZ9nFfPAUk+ajre23FHqTf1
            m7CnASqWYz14SqSnDojqJAPFNKK8JN5xLRSR/797qXQzobM4KmJHfd42zwtB74aW
            iyVeNiXEU9RyU6QhkfvBHPghqMJ2ANBkBjXR6KsWBIbW4u8LLqnYD5F9aXmDyUVK
            h8P3LVgA36VfxMo8wy6M91uJM8KtJddFtn/yqNTjbUGTj4cUufJIZoCbxy4bsSmu
            Jm7gQ/k2dVB9LLbqSl74lPavdnMCbw7D5dKmW5uOpFprOlCfcghVQVQV1gD2hjnS
            4AHkfjua0skiKyWSN4VQ1B13jeEV1OAT4P7htnrgu+JAKvvm4CXlE1lEJmw+hXGL
            c5+Im0Fj9a/ASrzUGIWwvbKdL+Et/ovgMeRG1/+6mCKby3huEoFI8xAj4ldSemnh
            UlsA
            =sFDN
            -----END PGP MESSAGE-----
        fp: 954A3772D62EF90E4B31FBC6C91A9911192C187A
    -   created_at: '2020-05-27T02:00:42Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA4SNlT+wHnqoAQgAgYunS7rQFApEl0qw1/1udTT5t7+SnmOfJEsYQLA1+9B6
            Ts7kKYse3leKY3KWpclffFnp1atoGuLZUtfG6sdelqKl1Xvk3wDXAJcoUMP61uys
            d8mfoaTD1KTo+ArTCPwtJtdQ5Cz7/CCvQWCVBi1R7JVnPs+y1bXbbpVR+mW/CPT4
            00Be0ErMcBFfWzeo58pc2AnwUYZlWS1IN3/3lnooZ0KqVyfl4dAD/Qp6Mo4RPJyZ
            ldOxNS2cULAOXTn2aZ2mqAVQHPK61rPNGokb73wdoLClCIbFu1RSR7eERgtCUbuF
            5hGWiJxGtreS6nbcgHG+c2QvpZLzMBVJbcF00xts0dJcAbQltUB1VYkp6aornC/5
            jfLNuiK4ghs8SzgQPLj3DzS95CwSssSXndl+0Wse9gZvRwdR0yv5IvvKWg5XKmXN
            JVdsGMThNvGv3BB0h4k+/NB1iD5xaKldbUlEQF0=
            =vnPi
            -----END PGP MESSAGE-----
        fp: 8333F292B1BBD334A61E6F566785F7AF28DE7081
    -   created_at: '2020-05-27T02:00:42Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA82rPM2mSf/aARAAJ4m6V8/X/JnXsEpOoFJ2+5MaP/Ze15CLzJKz7mf5XpgM
            Wwgl7QvaPXcLNE+G854RKU3mL5EemTGIfeS8OLJluIx9PA5HZlwucNZXXNTdgaet
            XfSBbZOFDZWq+RCri2mb4AKY8Kcg8mK1IM/I5fc/wZlONC5JW7cFWNliTUsgMIZU
            lJjcgBVH3Geu4MpW/4fPzAVj0XOYJpkLQyMpbOwRx3ytdohE0CCLxCv6h/HcsqC9
            iJD4sluvJLlLh7AftzciB+eVK/N2YlUz4nOBVTK0vekGz6tu9lZ1s36HRDp5uWy3
            Td/EkcavsHq3ovtQzE1AHgaCmp2AH7YOejuIIydDrQbs6utkQCIA2i0waYTWGuD6
            XjNUjXRHaJkRtClZAZJj88FfesZO6GcLn4QvMP8/kuUZJv6M86huaAlshvuI9CfK
            gMG8LMVshGA2k52pD1U+wNV3/uGSeUCo6zTegZVuNXcEEzsbXP1xEaNdx4oNg/nC
            Fko+skLERuVqnyq1XR3xCSOFgbbbbiWVzPy384FMUKv32HChC20vF6FcHkG5QHcd
            RsEUS9d8cdUnVaq04hM1xWXkbrsEhPz7D7Fo02ZkWjQnHrDSCWI/nksmBGnPjv+E
            pfYLQChm5xv+B67ANztsM1f4qTkUmSUrRH8vdd6Audeoyfg99uOmAT7LVzFspAjS
            4AHkAKAhzYuhXZ9th7JpDus3CeEQx+AD4JrhiIbg1+KOZOtg4PPlaQrPgAMB+Q1M
            50vvvXc9pNDbruegGCU2C7XP3rIbIf7gm+TU00U+o3uaMkAtjx6wO5tY4h6QcVfh
            +fQA
            =ZhIK
            -----END PGP MESSAGE-----
        fp: 6B61ECD76088748C70590D55E90A401336C8AAA9
    -   created_at: '2020-05-27T02:00:42Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6dhVUuTLV7oAQ//Zq/oybcX2dAFVa5BRFa6nPMem3XEmgvxDUieFa6+ZOxs
            15D5v78OitI+sFYjrxwm4xbyQQuxGjdz9xeERkn1lDlKAjSXGs/bk6Lbu5jFzSnG
            W0e0Ie5IS+6GgpXjWgNkJrIg9VD/eeWe8WNV8Qiy3jCoDMzS1qnZ4YThwNYsVtkQ
            4zgWTOpVntKxqXHSEzOF+ydAfW1w3/anrDtBJlg0BbKoYkfJ0xhVl6MmJjEY+pFL
            BmEv8F5rKkjNVwaCfqSUyndV8jsW6KgY2VpaSlblWuLK0gPR7FhlV8Ea0QiUhTlo
            E5OEyT8/dS+qEUHMudL7Uw1sOGtp+4Q9jN0lyfUDoq9Rdr3lq6jGDIHz+/gWwW+E
            f08ATYXI45e7RLYaHOlECrT9JRTyS1ucZQeMTDz0jksTwxyBpz5k+yGXc7JQnmpQ
            tLRW6IfKl/mpKXGLkMFZkMEl+d3PIxbJ2BNgLhsc2P36Z3st4GVAeaqxpW2mdUTK
            OUvNpVAhH7PBZUZMvZmEq+wUNcjEQ1c0Q/L1mKLSyEc8BPO4HqXt4dKy1KCIvIB1
            avARFUcTjls6Q74Z2ervI1u0F4QnxLBdXYTxdJpHCu4ixcAl4FCBP/7kNh4CSyLa
            LbU8o3wEpg1Z0ALrL5jpTNipRu9VrPl3T6AbZXDsxqifUseoYbi2hVMOL1eZiNXS
            XAHyKcTXjnVEUV1gjX5XM0pqiCmeO4dz1mIus6ZuszhVojRrjcdRtxlk4ieW/cow
            q5h//hdO2LLtZEUnVRu43tYyE46WGgslematou46upyAUlGa7RV7yLz8bRtl
            =nP+1
            -----END PGP MESSAGE-----
        fp: FC2255B7BBC7EABD4EFAFA1068907D8BCCD85A5A
    -   created_at: '2020-05-27T02:00:42Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8KRInHl7Vz+ARAApe3kdg8sd+sCwzlfpWtHuVV2puVokKwHjwX0jVyOHbKT
            1Uot014SMx8rgblpbDHoD0dUtv5+a0+JoPKZ9u5R4nyLtWGLvh0BZExc1II3Eip7
            +gmk4X87m1iFwUu61VvxT03VSkfQC1XSUHsI/ZU8k/PQaQKbaCWod0jHC+f8WA62
            3v9fHWzuQKCspmprKr5zKBGYHzSJZ6OF0OlQMb0QzxJHXdedAG1eA5aRQ0U29cbD
            7vnsWnpIBZ/6jQyqwWKV6rxtqc3ciWe9PK+dAli5amVnMfZYTPoRgUjirDh7gu2R
            IWivyLNjdTw4gxR/3gLXQSV5VIZzJvpO8Sg3+pCsiGLeENi5oyn5lJ6O+NBhlFHW
            dkNLsZzH5RkhJs8xlqIfKs2EYEn+H61RykxMuhHG4FWtMv5OeeRn0ILobevnuU1P
            hgDubTTHtZ7gQ9Z6h0fPKbI8cR/utdOLi1Zau+4QTZavNDy7ByOl7bi2RT1H735J
            m0Zt3oVfZGHFMtCOKqOayLxKjsm0Rmtbdg+NVW2yQ4j3LBKuEatJJFN2dq1pPbUO
            gpONHcAfJTCso+5JJrOWK+7IlBwIUX2YKlvzCYlmPYQMdsin1AWyzL/9Zw6nuxQ4
            xaIQEboTqIXqEYeTatUsaDPlmUQ1en7IHodEi3OXXCsmiUiVrpZkj2gIt0aYciDS
            XAHCZS8DUC2rrsz1SoOQXajrFbW7zctfq7oLF595PuP8b+sBErvExS7p3PzpWUNf
            8DF8wDj6YQBZ2y5lX0pKSH1vpR8B+JkJMIlsunohF8635rjoqOf9kj1EBOz7
            =0KcW
            -----END PGP MESSAGE-----
        fp: C92FE5A3FBD58DD3EC5AA26BB10116B8193F2DBD
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
