apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: userdb-metrics
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    prometheusInstance: default
spec:
  endpoints:
    - port: http
      path: /rpc/metrics
  selector:
    matchLabels:
      app: userdb-api
