apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
bases:
- ../../../../kustomizations/keycloak
resources:
- namespace.yaml
- ingress.yaml
generators:
- secret-generator.yaml
configMapGenerator:
- name: keycloak-config
  literals:
  - KC_HOSTNAME_URL=https://keycloak.ryansquared.pub
patches:
- path: keycloak-auth.patch.yaml
  target:
    kind: Deployment
    name: keycloak
