# This is a temporary file and should be removed as of 2020-06-30.

apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  resource.customizations: |
    cert-manager.io/Certificate:
      health.lua: "return {status = 'Degraded', message='This is a test'}"
