apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - namespace.yaml
  # v1.6.2
  - github.com/argoproj/argo-cd/manifests/cluster-install?ref=3d1f37b0c53f4c75864dc7339e2831c6e6a947e0
  - ingress.yaml
  - argo-cd-service-monitor.yaml
  - argocd-notifications/
  # Projects
  - projects/default.yaml
  # Applications to deploy
  - applications/argocd.yaml
# - applications/book.yaml
  - applications/cert-manager.yaml
  - applications/cert-manager-issuers.yaml
  - applications/external-dns.yaml
  - applications/ingress-nginx.yaml
# - applications/ircd.yaml
# - applications/monitoring.yaml
# - applications/mtls.yaml
# - applications/site.yaml
  - applications/userdb-api.yaml
# - applications/webirc.yaml
  - applications/website.yaml
patches:
  - argo-cd-repo-server-ksops.patch.yaml
  - argo-cd-allow-alpha-plugins.patch.yaml
  - argo-cd-import-pgp-key.patch.yaml
  - argo-cd-repository-credentials.patch.yaml
  - argo-cd-rbac.patch.yaml
  - argo-cd-allow-status-badges.patch.yaml
  - argo-cd-enable-jetstack.patch.yaml
  - users.patch.yaml
images:
  - name: argoproj/argocd:v1.6.2
    digest: sha256:b9ccb2655ea8784788b61a376b68776df4d4d0595fd603f12ea0724cbc31eb32
  - name: quay.io/dexidp/dex:v2.22.0
    digest: sha256:01e996b4b60edcc5cc042227c6965dd63ba68764c25d86b481b0d65f6e4da308
  - name: redis:5.0.3
    digest: sha256:4be7fdb131e76a6c6231e820c60b8b12938cf1ff3d437da4871b9b2440f4e385
  - name: viaductoss/ksops:v2.1.1-go-1.14
    digest: sha256:47203d9b5538f11f16073ee0f3fd4ab99a2254188cfc043895ff65a663b06095
generators:
  - secret-generator.yaml
replicas:
- name: argocd-server
  count: 3
