apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - namespace.yaml
  # v1.5.6
  - github.com/argoproj/argo-cd/manifests/cluster-install?ref=f46333ea82ad2157baffc5a8cf02a86720d4bad4
  - ingress.yaml
  - argo-cd-service-monitor.yaml
  - argocd-notifications/
  # Projects
  - projects/default.yaml
  # Applications to deploy
  - applications/argocd.yaml
  - applications/book.yaml
  - applications/cert-manager.yaml
  - applications/cert-manager-issuers.yaml
  - applications/external-dns.yaml
  - applications/ingress-nginx.yaml
  - applications/ircd.yaml
  - applications/monitoring.yaml
  - applications/userdb-api.yaml
  - applications/webirc.yaml
patches:
  - argo-cd-repo-server-ksops-patch.yaml
  - argo-cd-allow-alpha-plugins-patch.yaml
  - argo-cd-import-pgp-key.yaml
  - argo-cd-repository-credentials-patch.yaml
  - users.yaml
images:
  - name: argoproj/argocd:v1.5.6
    digest: sha256:a805c3c90936d8d43298b3c73c7ef99dced6d22f8f7f6285b648233c3b9be5bf
  - name: quay.io/dexidp/dex:v2.22.0
    digest: sha256:01e996b4b60edcc5cc042227c6965dd63ba68764c25d86b481b0d65f6e4da308
  - name: redis:5.0.3
    digest: sha256:4be7fdb131e76a6c6231e820c60b8b12938cf1ff3d437da4871b9b2440f4e385
  - name: viaductoss/ksops:v2.1.1-go-1.14
    digest: sha256:47203d9b5538f11f16073ee0f3fd4ab99a2254188cfc043895ff65a663b06095
generators:
  - secret-generator.yaml
replicas:
- name: argocd-server
  count: 3
