apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  source:
    repoURL: git@github.com:RyanSquared/gitops.git
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: book
spec:
  source:
    repoURL: git@github.com:RyanSquared/gitops.git
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  source:
    repoURL: git@github.com:RyanSquared/gitops.git
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-issuers
spec:
  source:
    repoURL: git@github.com:RyanSquared/gitops.git
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
spec:
  source:
    repoURL: git@github.com:RyanSquared/gitops.git
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
spec:
  source:
    repoURL: git@github.com:RyanSquared/gitops.git
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ircd
spec:
  source:
    repoURL: git@github.com:RyanSquared/gitops.git
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
spec:
  source:
    repoURL: git@github.com:RyanSquared/gitops.git
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mtls
spec:
  source:
    repoURL: git@github.com:RyanSquared/gitops.git
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: site
spec:
  source:
    repoURL: git@github.com:RyanSquared/gitops.git
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: userdb-api
spec:
  source:
    repoURL: git@github.com:RyanSquared/gitops.git
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webirc
spec:
  source:
    repoURL: git@github.com:RyanSquared/gitops.git
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: website
spec:
  source:
    repoURL: git@github.com:RyanSquared/gitops.git
