patch: |-
  op: replace
  path: "/spec/rules/0/host"
  value: argocd.syntixi.io
target:
  group: networking.k8s.io
  version: v1beta1
  kind: Ingress
  name: argocd-server-ingress
---
patch: |-
  op: replace
  path: "/spec/tls/0hosts/0"
  value: argocd.syntixi.io
target:
  group: networking.k8s.io
  version: v1beta1
  kind: Ingress
  name: argocd-server-ingress
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  source:
    repoURL: git@github.com:RyanSquared/gitops.git
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: book
spec:
  source:
    repoURL: git@github.com:RyanSquared/gitops.git
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  source:
    repoURL: git@github.com:RyanSquared/gitops.git
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-issuers
spec:
  source:
    repoURL: git@github.com:RyanSquared/gitops.git
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
spec:
  source:
    repoURL: git@github.com:RyanSquared/gitops.git
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
spec:
  source:
    repoURL: git@github.com:RyanSquared/gitops.git
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ircd
spec:
  source:
    repoURL: git@github.com:RyanSquared/gitops.git
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
spec:
  source:
    repoURL: git@github.com:RyanSquared/gitops.git
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mtls
spec:
  source:
    repoURL: git@github.com:RyanSquared/gitops.git
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: site
spec:
  source:
    repoURL: git@github.com:RyanSquared/gitops.git
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: userdb-api
spec:
  source:
    repoURL: git@github.com:RyanSquared/gitops.git
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webirc
spec:
  source:
    repoURL: git@github.com:RyanSquared/gitops.git
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: website
spec:
  source:
    repoURL: git@github.com:RyanSquared/gitops.git
