apiVersion: v1
kind: Secret
metadata:
    name: argocd-secret
    annotations:
        kustomize.config.k8s.io/behavior: merge
type: Opaque
# github webhook secret
stringData:
    webhook.github.secret: ENC[AES256_GCM,data:7QTiyK7/P/C4L8TNU3wHwx63g5/ztR9+AuJHl1QK+PTYwdpFxMToKg==,iv:KgeMs6c3UVmaWwSzPL4DSJMOvyOxsbJ+DGEsBMwiycg=,tag:/zm8hlfG16NAOeDa7eGAbg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-05-31T14:47:00Z'
    mac: ENC[AES256_GCM,data:JJoUmMA05TlXO6GiucALu0NrbjEYMLRhW28bCj25u5xlUFsCFTaVueFNBkBUvMEr9wgjemqImAf3Sx077NmKfUDenw6GQVUeS/2gPyKUBjZu5NxdDvjrx6K3d241WPrLyM3Ygtmh22ZJ4aWH/11X0v5aZxuOtDZyiAHvVRPqO2w=,iv:8y7SHpXz5vDpqJ71sY5ScsdqOrlZJVmYL2nAjEvSygc=,tag:cXQe77CH5OSOvS1dR1FTaw==,type:str]
    pgp:
    -   created_at: '2020-05-31T14:46:57Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+pWRuJw67SWAQ//RBi1QH5jcrQMrPDPt9ezmWvxMt7FYMl3OhUzBXSnmYDL
            nf8Yn2apQCnQLQ+eE7+nVhq9bQ2YnAN7S/oduqIdot2mgNF9lbQEH2+Ukw/VNJId
            Z2XANePSoOvX61pFvJB/7cg6yWcxxwVWBFPfIQJ5MMiI+wGua3LHbxpv33WOIPXm
            dr7CrPBuRcVbh0ZCowQj7ndG3Lmk9PNnvWnVVfAsDg6O9qMNxe2wmF2GQ5C0bCLL
            Rz7cS1JjdURsCyoak+W5YZq89zDoDoa5B/vqhCl5thKTDbJQJZhBehopRa/0doYR
            n278PD5BzsMJO2P1KEGrgl5qMDDPB5UowvHRMLGOkINEPj7qooWBrV9pdvAq2svn
            qlvSNidAFv6YGN6rZ0VkmOystuTGRdNTYCE9mu73V41hgulW2ooDajMD3XVsjwUF
            zMYCKq/c/Bzd4CwazIE3yUvzbwpg+WISltW8Yie1YF1nm3RMcIXB+7q8eww76xJY
            0oIb+E0s9exCwScVIW1qcYKwoYloAy0538sBpRug4ff4mFu/VtvtWH3IK5gVxxq7
            0YoVhdl6Gb62qKwLuvPRjMwccu1Fsc2CbLaCgYnSHg+JMfEK1zPRCCuThIIDvhVc
            XWUM5UTiLH61wx6I86O5z8dGEBgc1k//EvLrS3Abp5ZhGRhjaXPH+qrkuUo+Gb/S
            XAGNMsbvu469ycVswzvrF/iat3e8RBoF97vTftJo0J2Z+lrsm1NZ4qhgXJuH8UHP
            OyBgsJkRgmOXi2G5bBMKglxP8GKu3P7l5CUcA7LhzHfsLNPh7P+jKOncy51b
            =bhEu
            -----END PGP MESSAGE-----
        fp: 1FD6667A0808D4D48BDB8757A61B48D8288FCF8A
    -   created_at: '2020-05-31T14:46:57Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA4FedWMNSzdLARAAGJbeDL5t4GXwd1RH1LuhM/FmZGt40ZQbWA4bIFvS782f
            MjL8Kp30GY032a/q4UMgLoZbAPKi6pXhOb/LKXuJy+EEG3phjnSivgH6qJLJxBfV
            ITs6FZNl06ODcZqJyjCssYvu058oM3/Twc9bHqkNRcLh4lPYmSuyWHekoEN+FRba
            LLmfl+u63qHcx2qcSi+f6k98wrNxYECQhVYILkYRmRVzd3cHSezlpH9aRDULWHJP
            x1TdzSNU+XD7kGfXCifYVMbIdNkU0QITnY7yOJmPa1I/fBFRAu+0yYgcAbVZWUJP
            KFxgtU7680oi+46Ryq/BpIHQuRyTjQlbGUAcN0YwFQMy2d8pHb/M0DEtinakbNxV
            zWRpWmuqwzakh2NJYCXYJVY119zUU11OCYO0uQDupo16Vc8HPJ75YVA07w78R11o
            dCqjXS+74PsxUHfw3vYtqfkiMfnzRA5mR4mcV4iy5m2W+6S8DUT0uyb4wExvWGFv
            JBYV3vO/2fwvYqjsHKP30CemW4pWH6YFsJjqlYgPYnYoyaRwWpeTgCwfEofL6RuP
            +m1ruRLBN1mgT/QK5ZuEOKHcOnWgxNntz7+8ijXIIKzojs23XRiXE6I0vsVjD+5g
            3zcTddRvom8zN9qRXQyI0jbcY22Yaoja6S1CkQ07chJg6d9aUZh6eICeFxfk1AXS
            4AHkTQp2YHok1YTDRyD5f+O5UuHTdeD+4JPhowDgkuJqKWZ+4HblL7QA9M9L+aKW
            ZEFL4Ev+/HwjRxbD2FTqYA4xJg0p0JXgSeSMO0qz8L7mfCviO4Y/D9Ih4oDNXUrh
            sVsA
            =e+Ez
            -----END PGP MESSAGE-----
        fp: 954A3772D62EF90E4B31FBC6C91A9911192C187A
    -   created_at: '2020-05-31T14:46:57Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA4SNlT+wHnqoAQgAk+UpRST1UIA4o3cUPfMnKxmHOp4J2VHRtu3k4Kb/XTlU
            wHso3A8MEJtNzNrwse3PVXp3OhdWKp9hU52Ag8+Vv+ZQjq4h59QKl7wlVq28ksnZ
            NOgM9HeLLXMgshGT0eDzTPUO4jutMxcOPPaHxMw0NBW4EDNYPlDsCWLNbqGUp+E4
            cyNVliqJsOKbagnEx2UY/OB6qdXjL+46HrElxfKkOE87+RHoCmBwRSoi4FQ2S9zk
            SHmmPAFVE6ucQx7cq327DN0l+rzTFChnKcPxq15fI7BLyLXehl9edyDebBF1ttTN
            uUSJe/On6Fu2yHgcsZCKtE5ajMjXjfaQdlvyXpQzzdJcAXzp79Ax6TUilwtSX4eg
            IgN31JDJkiu24prjHRIYXgpZQCo7JStesFdEJvGFIWc4vbfkzvPidDghWsca/42B
            jEO6CJz9owxpNY41kQyhcVYHFeFwRDHt7R1RQX8=
            =7mQS
            -----END PGP MESSAGE-----
        fp: 8333F292B1BBD334A61E6F566785F7AF28DE7081
    -   created_at: '2020-05-31T14:46:57Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA82rPM2mSf/aARAAGtI8kFNoWqunQLbgp3XiKpBtcqtULmkdUaJtjRbpDNsz
            LJiQE0xT+dz+XcDFvRahCKXrmVcEg2oA9M5pjoHQoCj1c8Ke7EwKPXuR42VeSczh
            s5P/MMHl/+9RvOQ3Cn9/Eww7Jg1sB6yiVNn+wO2YSf6Xk9WK4zHC883euwFSu/Lc
            PoNy012Chnpap2uDo/2aw9H7p1v+JXcyA+/F7g68MR/uIeEodu8KuAP73NXYeEqf
            px6AUhF3NKHvWPl87poVKohLWiJRb2I4moRhkpLXKwRM++gGZbDUvX5F7K6T0yYr
            sU6II7t32fp9ntMwbI5pnJsYtYRsBnspmla9i9QHJSnk8v/ZXYWHA2JMYBol2SI4
            aOgQ7Fx5VXDESzaggowQSR6xnJ9X9RaOUJVZH9aFcZ9F0U5LqbFdFgNOWrhbLGjk
            faPfOXKSiXyQE7rpLIwsBzWGJ98+SlXbdvHSkDq2+GQry+vfVC0oqfh3BtQ9EoXl
            u50Jr4/XJLxoi18izH0tFeaB/HZB2C6NlmXX3kPuleQjcgC6eQEsmb+fRegjQgQK
            aFZj3ulk7gdisfdZy98sxwfJp2cQXTPJGqvip2yYbEbIni1FRHHYr3NnqcfRMJ44
            0045Cx0ySG/gIU2XzIZf/AhUqq1x5WECwdNO6zZf2KHEdWxG35h5xgJFHBeadlLS
            4AHkOK8mMW+ELFAyoBNRbHrv6eEHHeAl4CLhp+Lg/+I24N3m4HblkxTTycjSVq5f
            jBkaqRo0gWKCyiR/I1q9cWFbtdTbpyjgpeQcBAq2Gdmy83gp7GIEbiFX4nG1UBjh
            rzkA
            =PHcN
            -----END PGP MESSAGE-----
        fp: 6B61ECD76088748C70590D55E90A401336C8AAA9
    -   created_at: '2020-05-31T14:46:57Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6dhVUuTLV7oARAAjtpFRDlKyrzl5uQPafbd9nLWE3XzlCMv66k//BD39J9o
            9LoQQgymL0Tunx1YzrpxHJ5wnBCgZ25o8a0ERJHxjFIVySpEMVKMRXJs88joBkb4
            EA4j8KG4NzFh5IFKQfTMgj1W47r9FtrgWEqVApsEU1IAwh9j6EKR/9IozqtdNFkd
            Y3R/Ze1P92XaiIFDEvnFGX+w2n5KPKr1WISBy3nZ+Egmdib5rrWJL4f4BxkG5T2J
            it44+Ckk9ZcYWoJ6gHAZ1uHtDSspzGDsrWBTOZOiuneG2nXIvvQA2CRqd05eK5j8
            AjeqPLkkZWS3hkkKtLeEFqMRgpHhmpiiWfya+jfP42Nl3TNDM6GHBjhxPdZ/h12M
            rxVxFlWDaepxFmFsFO8hOJCEPqPFMm5A1QYdMr116E1O7dArLxz1ClFuLNKtDwip
            1G/jUUT1GDLY+XJZVwSZk0fevsyGIW+rzRN0UPhyhvSPxjSVT3pxGZ+2+KTHUeNV
            PuH7ZYZ/EJE1K0U+er4c9AT1R90ymGIkeH8LQIae3raLGTniMUbXKbDIL8lpLMkM
            DNLsnjPXBOkrQFRWcWC1/K0rJ4MYs3qui8BRU2uBvAs1krS0cCLPPjIEnkF4AgEG
            HKS1vhtMH509C9l5MyQ6BmM0FbFf7/+0npEESLqXqCH1akpmmGXUIfQYLpS0qTvS
            XAFU/pRiQWYJ/HXOkexHswTP2a3ykQumP3tBkUY1CzUdhbvXoHWYfk+ZGDve2Hku
            92f8BkRxy5pWTZRhPt1XG+CGL/XOauLb5dOQAQFzRZyTGcMal9yXZDR0IB9b
            =t53p
            -----END PGP MESSAGE-----
        fp: FC2255B7BBC7EABD4EFAFA1068907D8BCCD85A5A
    -   created_at: '2020-05-31T14:46:57Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8KRInHl7Vz+AQ//WGgK1jHo5VmaPlFQ1p7nrMWkoFLjQ3OXmDK9dXDAXLyr
            /GMR1rlgST84MuX/Ov/hE69RVnnDi5xM1YeZ37F/cdK9PJHvl1fRbIDHaw250d53
            Fw69IwLOUu88cF4qlJi+DjKyzo1X3jAk9U0Opg1Yk/XZ4FvX52QlOp6a79z2jA6t
            Lfgc3YCgpInuT7b3eU+bcEzShcP+9rstaM4vd5VbfcAOetYpIs261fY5UYMCRrdG
            9+SGLqL7ipLUwB3T/krmwP57eohOFm+NVaGvQCZt8L+eH9e/ZCYBmZGhv3MvMoUQ
            sqVrZF1TEu/JdRaL1zNrk2+L+OSDXYwTPpExCxpxZXo2new6EcDmsCzBc3Jkm0SO
            T94pjj4AjHwr0GCnc14UzYn3Shu3YYoGWppP4YXqdtlvP1ZEBh4VssM7u/JvgG7S
            Ka4rkUerB1Yh1KVxhjElbCiwqHx2L12KVTQtW44ZpaVldb803+lGrMXZZNxknUt/
            uMYr5JOL22EMiuoWqwzrzNmN7ymNmTItl0XiUL7PEJ9Nan1Vo4h2NBX6B4dZcw38
            4z9q86pT2AvNjGyACs3A4Qf76ScfCD/cfZtelNT9lqpbxjtHbHWLcSlo65gDyQLq
            hAujiGznQaZ/OJPW4z7f8iw5YHZ/0XUfstpaNlUjuxPWIwUeNr0RmHnKUa8ND8bS
            XAEnZy+bEE6FA1Os1cyjZ/cWqUiEbXW863uX5b6DS+wuUICfVatLw+CZSOhUYP5N
            1G4uTT4Obbro0DMytM2jKQwz0Z6nvmqhqqxuyqaA1GKAWV4f4dwsy+31bz4A
            =Up4n
            -----END PGP MESSAGE-----
        fp: C92FE5A3FBD58DD3EC5AA26BB10116B8193F2DBD
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
