apiVersion: v1
kind: Secret
metadata:
    name: dns-iam-key
type: Opaque
data:
    iam-key: ENC[AES256_GCM,data:EN9tS9AZnE2rEmpLvbRu3y66HCx1tQxNgf6xQ85J3plQySux2bIFKuc855YEgSuB3fnxCM9zwdU=,iv:aaTvqUnfKeLPti7/VRQbwACWo5BveYSKi9pufW2q0p4=,tag:RoD1HBWwuNxyh0QcYbaFPA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-05-26T10:02:08Z'
    mac: ENC[AES256_GCM,data:+/hMNEjxG589mWqR5fNloO4o0xTR1cSuchtxYf8jOUGf8nNB2vZHENT/4yFtmbfLEzK/5ujC0TlC4FsZQvwrFtoRfbnfQ4H7+6yb21s4oDh53K6hRMdujVeeQzwYEfU44TCY8ZyiNzEVW9PuNgm7sRrm99RD29hIDGakICW41b4=,iv:yEV1ghjyFnjY4j7j4eSariada/76EPc6h3+89TFEA00=,tag:MwzdIX/KVULkDNJWY+9ozg==,type:str]
    pgp:
    -   created_at: '2020-05-27T02:00:36Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+pWRuJw67SWARAAt7Jl+G7R84pOL/LoJxXgxDfFWhHT0x/pVJ9Vbtshe31Y
            m5uk2/s/3srrRC3724Tt4hAxulK0eeFxfqXL1+e+ARUsGdQmJeQWlTbKuNWlCozv
            EXsUzH2BHHj1YC8VZsB+bZjGamU0rKGR1ho3alvIwyzBZT0iJEp1sElXXpWWIj+q
            4ZKAu5fk/LJXAZx+iIVlCDtmONl+QP/7e7InBYtc768ZobJTrlAXD3fkJ6LzMQaK
            hLpSyDTtLdGcZI9LerBbDi/xg3BeFcrjYEOZbZO8tX3HLlChirXk+Pg10aVf3yd8
            2CM1tHfGj9Y++nJRaiAN4AYRkMUs3pHgw7VTvTH92oN7RBv6Fz40465UFwmGqtkR
            ji1V+eqrcoGpeKL9bGjtW5MzpTOV+Flzq1Hd1FuhXJssu4rxGQhCUYncACKwVkHU
            3B7OI6TMimOgChZSvL+3A5HwDfQmfNNXIicRc3DwEE6j9hlRgFHz7O0MY83Cqrfr
            1007ZHmtBNUyH3PhEybCozV3FGjQpQojH2VwpzAJ8GyO1oFp+9D/GJcsnvqfUh0J
            OqL6uXa6ucmmjABtV0f9uNgT/ciLG9DxgzDckXOwjNptguQI4ZsxI36cXOhDM/D/
            rBbo5aRWZkTqWpM2Kd/ApR4mzaDSBBSYq+Srq/g4Nw477ymnJyr1FPZZaSaHbVbS
            XgFPzLxwoBBl9VZmalv3Z02gJ0DAfgoZK2iAvHqmvE8xG6Zww0uLzjMaQmjLX4sI
            Qzw6xLB6U9fWQmJYZgVrmIVH6ZwvAJVKbfv/XeWDzCOx5c3UME1w4DTJltOwBq4=
            =nXM6
            -----END PGP MESSAGE-----
        fp: 1FD6667A0808D4D48BDB8757A61B48D8288FCF8A
    -   created_at: '2020-05-27T02:00:36Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA4FedWMNSzdLARAAg3E9O2koupz7+N3H53fANxRQMGobw1ov5zyxVEvuG43F
            OCltmeWtNqaj+ssfyLxUMLJWsvPZkGhxIProXqOu+eOu8ac6IUdWoPW4VSnzFlBo
            3W5JBaQwR8gk68iRVedfDVEembqZ7dVrP9BgPi7+1FHzOJdQVxQN6WeP91I7Vk0o
            dFQELHAw2kzBwhC1j08N+GINYC7jkq34OhU1wqSNA01My0jMqS/Wg6TZsqId91gV
            nyWHzBJD20XQpmlQZi1a8r/9+wh6hiSCjVR2ahCNqo6h1Zi8mEKxMw3hBEylKv8B
            jmid+zg9C2HA4OJTmJZ7eMzwVEkvaVzXu1xIoSgtPMPx2eds0egQHlVODCYBIVl4
            N6gFcrG1S0M4sj8u8HBzMqCU3u27H0BQ7RRvC5ZJ8fPJKgOeK14WhNjct+WmYZ4M
            wN5BB0Jgrv2b464FWcxUGbc/Oz8y5i9i3EVj2jXecqkga2KP5NkBfrzVDxDnB7tL
            jt+chzTJNiHHSYuN+WpCDDpwOvb8b/x+kvB+akNHw8qWF3oU4lJWmu1ZlY6AqQOq
            1xga4E05SqIZz9YKbhripD0b8KjVS1fBM9mheKtK0J4dhqDIaRFqXgMFyefc8jQJ
            1HS0vQd0mAI9DOygRDf5u51MS/hcAaJIKzRWSgSpUNmNTG5kd2uhvz54l5rFyGLS
            4AHk6D0PThsWt+pRkbixnkWusuGPhOB04FThejrgSOJccDrb4KzlBIcIASxTxeS4
            0HdZB0VPL8RXLdMJOwXpQlwlK0rbeTHgy+RGXcSf5yxSLsKt1d7FNEVu4iRpGjLh
            zYUA
            =gldl
            -----END PGP MESSAGE-----
        fp: 954A3772D62EF90E4B31FBC6C91A9911192C187A
    -   created_at: '2020-05-27T02:00:36Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA4SNlT+wHnqoAQgAgEvV8GeRE79bOx4JGlLFLtw06rjfboIYCdnUoTfc+4s9
            Y6uZVxaDCvPhe5FBRFL9lwqLOY2+AG6Yk/C/WolX8U3AuO196Lhs7IhcE9oGocB1
            Jsc+VNK0XoWcdamJ7nQHNeGwDdbCFUdQAWvfYO5cZm8CFLRlAZcr7js9fWZ+V3vF
            GqDXvYiqxdITrGXq94UfDIpx2gF7WM32tIv5UyevEXAi7V7DkwdpZ8HuFHvSIMwl
            De2kimtkCKlgBO/UajvOtRxMfp8zMIUPAmjLVkZ30W0WoMll7aSPBSGkKUVPRxJj
            HRP4ksx/h16SN3TKfX5eMqs+dtFXNo+3FtD/jQh2R9JeAUK8TkpW+X8uqE3RWpLy
            lIW1QuIADN/jUyxsNcbqTJ6exZKQk9Lyk+9B78VXWoBcZHVGSxQsMRxLNLcpNlP6
            vFY2PrM0yPQ1ig7fFzsXfWjf2Gu2wCbgmu1AkLghEg==
            =ldAA
            -----END PGP MESSAGE-----
        fp: 8333F292B1BBD334A61E6F566785F7AF28DE7081
    -   created_at: '2020-05-27T02:00:36Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA82rPM2mSf/aARAAKg5wPf+YQPeisMcULTXc5ZoIDZjRr3+sEEMOpWe2VLsI
            bMnBSAqm2YbinQXzM8oyF1nFUQvyms8t3KIp5/TCuwnRsiODSiWdrAb2CXB0BT7z
            T3XaxBy7jsG/h6gFLaBHQA7ToVLlpnWRwQxIBxervKJ1kd+/H+FLoOb+lmfDkKuz
            /8y1DImKo8FWRNsHE+YwNVR+bFvB0ILreMwEZ/xVTFzuUIUy5z0ZDRabSr54PKkc
            xqtC7dg3RFofd1aGrbci0UQmnkOpmtDNKk3HqRTNaXPNAg34jXzRqtkOr3qIs1YG
            v17sr2m/xN57Nx7KAISfPp8PkJANbOvL1aIVRjR3YK2EhJ8TSQXgCrSF6zioOGoW
            TUZZEHIN6e+ORB1l2uM8bzsCGLJap9RHnQipyg793LWpa904kmuU7gzaJBpncLw3
            YT7Vqm/QF5aQ9wDLoqApRSy02/3n/riNAY7UAbKVa6yPi7bmWcgzzOlTc0vkAwML
            ZHlJ+b3dgfiTyPgYMzqd8q7LCXh+fDhI13xhsYyXaJDmll825Ny8vVAExu4Za0ik
            cbjyBN8hBhzI8f7+0FpDm2sCiV9fKZD3xjEDxRouZXlBuPVI0oZmSUa2Omnq/0g9
            b+48SJhOsSLSsQBvHhNCmeGazcNZ456WGi6ppQcQtkxUrL7GQituYFkLtFTyzZ3S
            4AHkBNxf05zHw0PLpVq4AQMf0eFXK+Dv4PvhNu7g0uI9EV224GLl2fbVMYJb9+18
            npfhz0as8WOIgyG0ZS6D/P6obnPv8ujgdOQUHMrdlmMr6h8Cwsmed4BR4o1TCPDh
            kxgA
            =rLCe
            -----END PGP MESSAGE-----
        fp: 6B61ECD76088748C70590D55E90A401336C8AAA9
    -   created_at: '2020-05-27T02:00:36Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6dhVUuTLV7oARAAiY0hYsi3aqFpHefpEPf2X046Pqtt5rsc4iONrQKTrrxr
            mvd27qY21lTB1H9XQkpUYKOUHgzQ+MMbic2wCvg8OcC7mwcn0tfBYhh2H6KImL4c
            yofVy5JluUR0NagDSqphROJxFZnboy6fR4SFZ8+TuSJkS+pYpSjZ59XZe2CfXRVX
            NpgVcV0fWZx1FqjsWM6aroVg+6pS2CJ/VHlF972uXRpnjLPxwTr7ljMEery0XOrT
            eiMOvmMyMiV/FbCAkD8BOo4oLbh9M971rXLOdimaFUyfzAE9kPIcwhRRyLIA+od8
            qdOjdI+8EhYjQEVI7QhqY01e4xH4KS8Ldbrs1mnoY+fQS2U10i2s1GYWWBLK2Jvo
            VNc1MitPWMNWEYOE57f1wC7LNKREF7bCNBSKAcbdmuT1LCHLfHPIhCK/l2bUUWab
            v1FXtxYi9Z198sSQSnDIA6IaZIXwTBXSCkUxvG/6pcP3LKgVvdl8x4sMrOqQ90FA
            YqbyBDIYDGvg3K/56WZTuN901I2rgw28m7eDA71uUVZL3E2+V7L6gauR2Vd0pYoc
            hLkYaJZowYQrXanBxVMeQelW923vKDxFEX5ry8rlqCLrVE9SMT67r02jLc+w8mK2
            fqmHuCzsuWLGEJsdwmJeOCIqMh6taIAPpVSkqqDedpz3Ev0MemCSIgpfsj1fiTPS
            XgH7F9R28zKjPopOJSykvLnr87xTYgNeYtPAD4B4FZExxMPRXvKgg96k8MLBGZfc
            +od+1sARmP4ryxvX5qT1OrB94tttRf+33PKkEoSIWuDlwpPGuxwaFE6OwGhS0zc=
            =rwcE
            -----END PGP MESSAGE-----
        fp: FC2255B7BBC7EABD4EFAFA1068907D8BCCD85A5A
    -   created_at: '2020-05-27T02:00:36Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8KRInHl7Vz+AQ/+KMnZp6Bpb8A6yqKxmgqjqJbwEaOJFkBdkpcJmyKJDxaP
            3JZEEpeSSqutDo95vTQznk8+L89lITVv2ZRvYK/peiSSabcxpBBUs8/s2a1+15Ze
            XErq3u8AiZ+XcA9qSHbVEoZRQ12ht+yI+QyrhdVyuL2GvWXCLJNXV/rzWrSFrr6s
            i5dE2Isqz3YPA8HcNo+wBc6CAxJzW5GC/AzWMMgKAnbOjjSCQc//z/4TRXh6hvPF
            OYTXaI/nwa+VrdKZDA/oichopo3L5oKFhJ2J6D4c5ycLFisPSJZvByZVUao1jsFF
            WYl2m3JRl7ffFNmtehIaSRURbC52CLF8mYi4AdLqHsJ2Oras9RVfyWdhl2lePIFc
            W1TX5/jMR6YMPEDDKx1ZIFMJgrbF636V5aL+54TQSRqRVnCMwtfQZAwGX6eqM43J
            Q07A3sWA1DBY2fPUhbVgcupZFyfc1xaBJylDbN2mObOiG7Tkl8cnFLQO16cw1OhN
            0By9snUSy+s6vI5GFdPxIUqgPp3V7SMmH4Ytov7Q5kyU91vwDcxBp7VCfxyK+30h
            CmjR38ejr8rQ4+OL96G5g3Y5nJO8Hu7QDqfBVq/wGFHt2zDp6ieYzVgwMSveSZ8j
            h/KbPBF+UycG3sVCnDdHvP48K1nM+WVZDA9DqPn3MKgvv+85k3LF1j4Jq+DTPV3S
            XgGHEYcE2CgQ2109fqhqMGL644KtlsvqX+aTZ23Q1wOOKO5nU0O0Uj/nF7uqfnp+
            Pw/l5PiqTvGbvtJOuO05Nsgxy4/pJCBhffWkrhsKt8rJYgsvL3qJMaDCmv+MqTw=
            =1QXE
            -----END PGP MESSAGE-----
        fp: C92FE5A3FBD58DD3EC5AA26BB10116B8193F2DBD
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
