apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: vandor2012@gmail.com  # TODO variable-ify
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: nginx
    - selector:
        dnsZones:
          - "irc.syntixi.io"  # TODO variable-ify
      dns01:
        cloudflare:
          email: vandor2012@gmail.com  # TODO variable-ify
          apiKeySecretRef:
            name: cert-manager-dns-aws-secret
            key: key
