apiVersion: v1
kind: Service
metadata:
  name: de1-shell-server-exporter
  labels:
    hashbang/shell-server: "de1.hashbang.sh"
spec:
  type: ExternalName
  externalName: de1.hashbang.sh
  ports:
  - name: metrics
    port: 80
    protocol: TCP
    targetPort: 80
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: de1-shell-server-metrics
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    prometheusInstance: default
spec:
  selector:
    matchLabels:
      hashbang/shell-server: "de1.hashbang.sh"
  endpoints:
  - port: metrics
    path: /metrics
