apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: book
spec:
  project: default
  source:
    repoURL: git@example.com:example/gitops.git
    path: book/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: book
