apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: book
spec:
  project: default
  source:
    repoURL: git@github.com:hashbang/gitops
    path: book/
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: book
