apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  project: default
  source:
    repoURL: 'https://charts.jetstack.io'
    targetRevision: v0.15.0
    chart: cert-manager
  values: |
    prometheus:
      servicemonitor:
        enabled: true
    installCRDs: true
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
