apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-issuers
spec:
  project: default
  source:
    repoURL: git@github.com:hashbang/gitops
    path: cert-manager-issuers/
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
