apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  project: default
  source:
    repoURL: 'https://charts.jetstack.io'
    chart: cert-manager
    targetRevision: v0.15.0
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
