apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
spec:
  project: default
  source:
    repoURL: git@example.com:example/gitops.git
    path: external-dns/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
