apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
spec:
  project: default
  source:
    repoURL: git@github.com:hashbang/gitops.git
    path: loki/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
