apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mtls
spec:
  project: default
  source:
    repoURL: git@github.com:RyanSquared/gitops.git
    path: mtls/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: mtls
