apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: userdb-api
spec:
  project: default
  source:
    path: userdb-api/
    repoURL: git@github.com:hashbang/gitops.git
    targetRevision: HEAD
  destination:
    namespace: userdb-api
    server: https://kubernetes.default.svc
