ingress-nginx:
  controller:
    admissionWebhooks:
      patch:
        enabled: false
    service:
      type: LoadBalancer
      externalTrafficPolicy: Local
      annotations:
        service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
    config:
      use-proxy-protocol: "true"
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 256Mi
    autoscaling:
      enabled: true
      minReplicas: 2
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
