ingress-nginx:
  controller:
    kind: "DaemonSet"
    admissionWebhooks:
      patch:
        enabled: false
    config:
      use-forward-headers: "true"
      use-proxy-protocol: "true"
      compute-full-forward-for: "true"
    service:
      annotations:
        service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 256Mi
    autoscaling:
      enabled: true
      minReplicas: 2
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
