ingress-nginx:
  controller:
    admissionWebhooks:
      patch:
        enabled: false
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 256Mi
    autoscaling:
      enabled: true
    metrics:
      serviceMonitor:
        enabled: true
