apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: digitalocean-csi
bases:
- ../../../../kustomizations/digitalocean-csi
resources:
- namespace.yaml
generators:
- secret-generator.yaml
