apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: website
resources:
- namespace.yaml
- resources.yaml
- networkpolicy.yaml
replicas:
- name: website
  count: 2
images:
  - name: vandor2012/website
    digest: sha256:a8cbcae784396bdcf312c7864597be64de2ed6a42a5d93224d3f10c679a99d70
