apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloudflare-secret
type: Opaque
stringData:
    email: ENC[AES256_GCM,data:V0vneB0rlWfZbS6RLz1R0Y1ZxJ4=,iv:rkLWg/jmGF5u+cBeS5cKMuPhlwqCuXoaJoN+ce1pzxM=,tag:4EYXMNW65Cu9cBVYjpVWUg==,type:str]
    key: ENC[AES256_GCM,data:jtZshhuvIhhtcwhRQYSOlTur2A1ER5aHkhGkL+CqvHqjWcn18E7bDg==,iv:Zu8Og+4BjSEG7S64FSZ2JBCpmtEtHD8JywPgP467yzo=,tag:t02NlVOduO7NG/xZmJTIKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-08-05T17:14:02Z'
    mac: ENC[AES256_GCM,data:QOUjTFyicxr11CPdc5g+BugtpuwJlpYXxN844UHU2oEbZ2q6FudOGTlpgbNLKC+OVET3q3qXp/KBwKx2oXwyWjHHp1YKSHExQVLh48olZ2yMnWIPHaZrQli3h+ABgNO8kUN1/p8Ffg5Q51CI0UX4gvahtsDAjWI2bjD93d/t1oU=,iv:BL2S2YKo+twqPlRGcfxeWMZuARmPsW0/srI13cQ7drc=,tag:/wpTH4Nj05N7SIOn695IjA==,type:str]
    pgp:
    -   created_at: '2020-08-05T17:14:01Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8PPSC5xMaBTAQ/7B+6aUeiARoa9iqtCH2laQAsnaUVURz7QgKNwrC3b6hSJ
            i3Nil6BRnEwZGwNF8PB3qp2qPUY2GDIDTHLEjhVBISRSgVemh9fS7FVHhqtgcT37
            M7XeiCPYAT2gsVcupg0pAH6QGHiWCiWWwQTWU5fvmwu8I6HaDtOP3y1evp+9wtsa
            ioSyDgxKjZ1rE8KtxGqQYT/3PGdOnT1WaJyLimua8Fjr2DA/tUnLz1i9HD+fYdrX
            uQB/sJFPF4avSfaBBxg++EQeKFD5H41PoTjuhQTdhY7JWHbU1IUKH5QtaD8y9jVh
            VsVAxBqOqsiixVJAQVRUpZN7uGOJHR05HUsMoq/566iEyoVRpM4vUTzJ2EiQK5Pq
            mfxB3Wvi1RAdWelJK1AxJdNLO9KC1gmLjH6np37ybRwzgeWA93Z8SFxxmRFLqJiV
            8ZSl/F3mGFUBCaLJs5XdpZ3f6aR4PdgpeiqLUw9tnZQdEWN8G2Pm6GqvnLlQBWX5
            Wpd8UM1FCermgQQK8wHQekbdvPLv5K1CMR8eYad+brlfN2h46LNhUwTcPJa7jino
            tStrH2ETcG+Z7bHx15WOLJO6mDzPWlVOKpbQUSGtZvXkJUYSPTaZiSBDvOCKXMv+
            fdBZLwzAU9ZVGVO2/v2rCtTq0d6OiwD+xIy85PgwSKS1oaYxKAzU3+OMQnj0i9LS
            XgHNgeQV/zQ/2ZDJksGZrfuTqTFae790LsnU0YiFQBF3YNd0HwWzHADoTeIfjZhH
            gFaQqio64TUW5duARfTV9HyRk7WTdLGCfpe+MLUuS7RQum65Uk4LYXEnXTIcoOg=
            =u2lN
            -----END PGP MESSAGE-----
        fp: AAA9C1DBA861DCC065C4337CC3CF482E7131A053
    -   created_at: '2020-08-05T17:14:01Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA4SNlT+wHnqoAQf/RQoTZdn7W/cFyQfQRcIYHGBtgcLiEeqW8iAcnFW1RBUn
            0ss3wDLvPEuQk+1B4IRCB3PG5AX8W3UFijBJyJgN8bOBdIV+zbqv76Yb0rjEv5Ef
            vFIi1ftDWPV043Eot7fAjh+0zhfVapxjD6XkQHD32sNRuvi+SoDZZgQcUjdLYrVR
            7kgTX4nuj4bsDXeeaWgsYkbb3iw/w+vC8T1tZm0aQhNwubnJqymqX1K/ENaDiYMM
            JDW7aYQBq/GTyPS19vmEBbkbivwEPEsAeiqqQ9bbqxBl+pP7w7WW2KdhK1xX028T
            9E0X4V4uK/fOcwrIiY10X0dckao4H3uP3jIFg2jGqNJeAQXV7GWNP9cF7VIEaC81
            5/aG0kiVyMGgxGOh950yit2IYS1k9r3gdgnRyvt8GzIRfCUotlBOpjVMq3te7EXa
            fLps+Py5ZiGbNHBYmzs4e1YBth0bQVzMXrHf8mPoNw==
            =oIAS
            -----END PGP MESSAGE-----
        fp: 8333F292B1BBD334A61E6F566785F7AF28DE7081
    -   created_at: '2020-08-05T17:14:01Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+mysOfPAHY0AQ/5AddutIyEa9vZzzh368Ej+COvyasKzksHhdw+DJypfSym
            g6gamfqHJNJVUWJCcQFjcDpbzc7VcVxU5LjaL5UJa0o1G4sqq1L7XEW46jdVhdWK
            2qCwrFc9scNYwIhoRCJErZhYncDrGbvN5NxXJGInnP2vkx8xjWEXx9GaNRSzHHCK
            nY5u72B2mRXb8PHbWhG+7xhlSdSXdBfRcAff5pIDGaT5p+AJelgZqwL/sv5vZaXH
            t6ZkwEFYkLEOHZ16NAGznJ/SVaRl/9s7Pkca7rnSHaNlIr6ksKs66HVXssf/d2lN
            qnJmqU3OrQZodSr8SKVcvoX9B+SJ6JWNSKemo0KymGYDiBgG3FvbJM4WVbvtBhWI
            0fjzrwvzQVurijT1d2TlUMRcyWIW3/3Q6H56CfUrixYsz2i3l/EFsWzFYj3lSV0a
            k6IZX/M6psyEPThe/SvsuD0L4Ih6DlYH/47XOO8VkJqQVrxqPa8Fc/Nmv/6yG9d8
            BpoBqa+yfVF0Kca6JjVh1i8Gf1Ai/3mA44egKWYyUX6dF3jRGE2pgS8HuBzd/c0d
            b4OpzvgQp9ouMjiZSGk7HOOA8H2VTD47OeLxv+Zji6DUdwdxGwbQ1a9NoIjJAYBO
            tiuOPkFwrRPrVeipHjRslFWh1bSp+eTRmqhEDrJxxDtqqKaQQ5IILz4rvPoFwdDS
            XgHwLDcrPc+x7GVTPdE6FXgskqWxOxSUyyrmvJdmo7a/ADrJ1NB48TGINJgsCyct
            LkD4llfCghqvCgO6jKxKjIcQIwJ+YV1qXeDJHJl0SlOe6OHOII0b58WLJpL3QzY=
            =I+fn
            -----END PGP MESSAGE-----
        fp: 2131AD2652633390D79599A5121BFD94928027D1
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
