apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns
resources:
- namespace.yaml
- resources.yaml
- networkpolicy.yaml
- service-monitor.yaml
patches:
- aws_credentials.yaml
generators:
- secret-generator.yaml
images:
- name: external-dns
  newName: eu.gcr.io/k8s-artifacts-prod/external-dns/external-dns:v0.7.1
  digest: sha256:bcd60418933d9092347c3bc98072e70404eb58c864ffa54396680066c080be57
