apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: mtls
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    external-dns.alpha.kubernetes.io/hostname: mtls.hashbang.sh
spec:
  tls:
  - hosts:
    - mtls.hashbang.sh
    secretName: mtls-tls
