apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  template:
    spec:
      containers:
      - name: external-dns
        env:
        - name: CF_API_EMAIL
          valueFrom:
            secretKeyRef:
              name: external-dns-cloudflare-secret
              key: email
        - name: CF_API_KEY
          valueFrom:
            secretKeyRef:
              name: external-dns-cloudflare-secret
              key: key
