apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns
resources:
- namespace.yaml
- resources.yaml
# - networkpolicy.yaml  # TODO figure out how to make stable (by Ryan)
- service-monitor.yaml
patches:
- external-dns-${DNS_PROVIDER}.yaml
generators:
- secret-generator.yaml
images:
- name: external-dns
  newName: eu.gcr.io/k8s-artifacts-prod/external-dns/external-dns:v0.7.2
  digest: sha256:da8f1dfcf7f9497b0fdd074c210385944abd231ff4f3e4dc10c60ef62a6b4901
