apiVersion: apps/v1
kind: Deployment
metadata:
  name: book
  labels:
    app: book
spec:
  selector:
    matchLabels:
      app: book
  template:
    metadata:
      labels:
        app: book
    spec:
      containers:
      - name: book
        image: hashbang/book
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: book
  labels:
    app: book
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: book
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: book-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - book.hashbang.sh
    secretName: book-tls
  rules:
  - host: book.hashbang.sh
    http:
      paths:
      - backend:
          serviceName: book
          servicePort: 80
