apiVersion: v1
kind: Deployment
metadata:
  name: cert-manager-cainjector-deployment
  labels:
    app: cert-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-manager
  template:
    metadata:
      labels:
        app: cert-manager
    spec:
      containers:
      - image: "quay.io/jetstack/cert-manager-cainjector:v0.16.0"
        name: cert-manager
        args:
        - "--v=2"
        - "--leader-election-namespace=kube-system"
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      serviceAccount: cert-manager-cainjector
