apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-webhook-deployment
  labels:
    app: webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook
  template:
    metadata:
      labels:
        app: webhook
    spec:
      containers:
      - image: "quay.io/jetstack/cert-manager-webhook:v0.16.0"
        name: cert-manager
        args:
        - "--v=2"
        - "--secure-port=10250"
        - "--dynamic-serving-ca-secret-namespace=$(POD_NAMESPACE)"
        - "--dynamic-serving-ca-secret-name=cert-manager-webhook-ca"
        - "--dynamic-serving-dns-names=cert-manager-webhook,cert-manager-webhook.cert-manager,cert-manager-webhook.cert-manager.svc"
        ports:
        - containerPort: 10250
          name: https
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        livenessProbe:
          httpGet:
            path: /livez
            port: 6080
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: /healthz
            port: 6080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
      serviceAccount: cert-manager-webhook
---
apiVersion: v1
kind: Service
metadata:
  name: cert-manager-webhook
  labels:
    app: webhook
spec:
  selector: 
    app: webhook
  ports:
  - name: https
    port: 443
    targetPort: 10250
