apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-deployment
  labels:
    app: cert-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-manager
  template:
    metadata:
      labels:
        app: cert-manager
    spec:
      containers:
      - image: "quay.io/jetstack/cert-manager-controller:v0.16.0"
        name: cert-manager
        args:
        - "--v=2"
        - "--cluster-resource-namespace=$(POD_NAMESPACE)"
        - "--leader-election-namespace=kube-system"
        env:
        - name: POD_NAMESPACE
          value:
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        ports:
        - containerPort: 9402
          protocol: TCP
      serviceAccount: cert-manager
---
apiVersion: v1
kind: Service
metadata:
  name: cert-manager
  labels:
    app: cert-manager
spec:
  selector:
    app: cert-manager
  ports:
  - port: 9402
    protocol: TCP
    targetPort: 9402
