apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
# CustomResourceDefinition
- cert-manager-custom-resource-definitions.yaml
# Deployments and Services (no Ingress)
- cert-manager-resources.yaml
- cert-manager-cainjector-resources.yaml
- cert-manager-webhook-resources.yaml
# ClusterRole, ClusterRoleBinding, Role, RoleBinding
- cert-manager-rbac.yaml
# prometheus-operator Service Monitor
- cert-manager-service-monitor.yaml
